version: "3"

services:
  openapi-mock:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./openapi/openapi.yaml:/etc/openapi/openapi.yaml

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8000:8080"
    environment:
      - SWAGGER_JSON=/openapi.json
      - VALIDATOR_URL=
    volumes:
      - ./openapi/openapi.yaml:/openapi.json

